version: '3.8'
services:
  mongodb:
    container_name: mongodb
    image: mongo:6-jammy
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - dbdata6:/data/db

  mesto:
    container_name: mesto
    build: .
    environment:
      PATHDB: "mongodb://mongodb:27017/mestodb"
      PORT: "3000"
    restart: always
    volumes:
      - build:/app/build/
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - build:/var/html/
    depends_on:
      - mesto

volumes:
  dbdata6:
  build: